name: Archive Frontend Artifacts

on:
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow
  push:
    branches:
      - main          # Déclenche le workflow sur chaque push vers la branche `main`

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout le repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Téléchargement ou création des artefacts
      - name: Check for Artifacts
        run: |
          if [ ! -f "frontend-artifacts.zip" ]; then
            echo "Erreur : Le fichier frontend-artifacts.zip est introuvable."
            exit 1
          fi

      # 3. Déplacer les artefacts dans un dossier spécifique
      - name: Store Artifacts
        run: |
          mkdir -p archived-frontend
          mv frontend-artifacts.zip archived-frontend/

      # 4. Optionnel : Publier les artefacts comme assets d'une Release
      - name: Upload to Release
        if: github.event_name == 'release'  # Assurez-vous que le workflow est déclenché par une release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: archived-frontend/frontend-artifacts.zip
          asset_name: frontend-artifacts.zip
          asset_content_type: application/zip
