name: Archive Frontend Artifacts

on:
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow
  push:
    branches:
      - main          # Déclenche le workflow sur chaque push vers la branche `main`

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout le repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Construire et compresser les artefacts
      - name: Build and Compress Artifacts
        run: |
          cd Frontend
          npm install
          npm run build
          zip -r frontend-artifacts.zip dist/

      # 3. Récupérer l'URL d'upload
      - name: Get Release Upload URL
        id: get_upload_url
        run: |
          upload_url=$(curl -s -X GET -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/KhayriBS/my-workflow-repo/releases \
            | jq -r '.[] | select(.tag_name=="v1.0.0") | .upload_url' \
            | sed -e "s/{?name,label}//")
          echo "::set-output name=upload_url::$upload_url"

      # 4. Uploader les artefacts
      - name: Upload Artifacts
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/zip" \
            --data-binary @Frontend/frontend-artifacts.zip \
            "${{ steps.get_upload_url.outputs.upload_url }}?name=frontend-artifacts.zip"
